name: Arduino CI
on: 
  - push
  - pull_request

# based on workflow from https://github.com/geerlingguy/airgradient-prometheus

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install ESP8266
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Install AirGradient Library
        run: |
          arduino-cli lib install "AirGradient Air Quality Sensor"

      - name: Install SSD1306 Display Library
        run: |
          arduino-cli lib install "ESP8266 and ESP32 OLED driver for SSD1306 displays"

      - name: Install WiFiManager Library
        run: |
          arduino-cli lib install "WiFiManager"

      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp8266:esp8266:d1_mini ./airgradient-zabbix